version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: rabam-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rabam_db
      MYSQL_USER: rabam_user
      MYSQL_PASSWORD: rabam_pass
    ports:
      - "3307:3306"
    volumes:
      - rabam_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabam_mysql_data: